#!/usr/bin/env bash
set -euo pipefail

. "$(git rev-parse --show-toplevel)/scripts/utilities"

go_to_repo_root

declare -a missing_required_components=()
info 'check command...'

if ! checking_command 'java'; then
  missing_required_components+=('java')
  warn "Please install JDK and export it to PATH"
fi

if ! checking_command 'adb'; then
  missing_required_components+=('adb')
  warn "Please install SDK Platform-Tools"
fi

if ! checking_command 'apkanalyzer'; then
  missing_required_components+=('apkanalyzer')
  warn "Please install SDK Platform-Tools"
fi

if ! checking_command 'apksigner'; then
  missing_required_components+=('apksigner')
  warn "Please install SDK Platform-Tools"
fi

sleep 1

if ((0 < ${#missing_required_components[@]})); then
  err '---------'
  err "${missing_required_components[*]} are required. Please install them to complete setup."
  fatal '---------'
fi

info "Found all required commands. ${_TADA_}"
